version: "3.8"

services:
  app:
    build: .
    container_name: arc_trainer_app
    ports:
      - "5001:5000"
    volumes:
      - .:/app:delegated
    environment:
      - CONFIG_FILE=config.json
    depends_on:
      - neo4j  # Ensures Neo4j starts before the app

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser (HTTP)
      - "7687:7687"  # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/mysecurepassword  # Hardcoded for now
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
